### ISSUE TITLE
Don't include Bootstrap in codepygments module

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/modular-file-renderer#177]
I'm not sure that it's necessary to include Bootstrap for the codepygments module. We might just remove it.

Related issue: https://github.com/CenterForOpenScience/modular-file-renderer/issues/176 - If we do need to include Boostrap, it would still be good to have a way to opt out of it.

**Comment by chrisseto** [comment]
+1
it looks like bootstrap is only used for the error messages.
Foundation is included and I think it could be removed as well.

**Comment by mfraezz** [comment]
While it would prevent #175, some of the Boostrap rules are necessary. Otherwise, it will look like this:
![screen shot 2015-08-19 at 14 21 05](https://cloud.githubusercontent.com/assets/5659262/9365090/9f6ca1b6-467d-11e5-83fd-442cd0ba6dcc.png)

Misalignment and lack of a border are obvious, but it's also not horizontally scrollable. A simple solution would be to just include the 10 or so rules that pygments actually needs to render things nicely in `default.css`, and remove the Bootstrap dependency.

Agree with @chrisseto about Foundation, it doesn't appear to be used anywhere at all.

**Comment by mfraezz** [comment]
In fact, nothing in `/pdb/css/` appears to be used.
