### ISSUE TITLE
ImportError: cannot import name '__version__'

### ISSUE THREAD

**Issue by rija** [CenterForOpenScience/modular-file-renderer#226]
Hi, I'm trying to install MFR and run the tests but I have an error upon install:

`invoke install --develop
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from mfr import __version__
ImportError: cannot import name '__version__'
`

I followed the steps in the README.md. 
Also looked at the Travis config as I saw all tests were passing on the CI. 

my machine is running Mac OS X 10.11.6

i have the following config:

`cat ~/.cos/mfr-test.json 
{
  "SERVER_CONFIG": {
    "DEBUG": true
  }
}
`

I have the following packages installed in my virtualenv:

` lssitepackages 
Flask-0.12.dist-info			decorator.py				mccabe.py				pytest.py
Jinja2-2.7.3.dist-info			docutils				mfr-nspkg.pth				pytest_cov
Mako-1.0.1.dist-info			docutils-0.12.dist-info			mfr.egg-link				pytest_cov-2.4.0.dist-info
Markdown-2.6.2.dist-info		easy-install.pth			mistune-0.7.dist-info			python_dateutil-2.6.0.dist-info
MarkupSafe-0.23.dist-info		easy_install.py				mistune.py				pytz
PIL					entrypoints-0.2.2.dist-info		nbconvert				pytz-2016.10.dist-info
Pillow-2.8.2.dist-info			entrypoints.py				nbconvert-4.2.0.dist-info		raven
PyDocX-0.7.0.dist-info			flake8					nbformat				raven-5.27.0.dist-info
Pygments-2.0.2.dist-info		flake8-3.2.1.dist-info			nbformat-4.1.0.dist-info		setuptools
Werkzeug-0.11.13.dist-info		flask					numpy					setuptools-30.4.0.dist-info
__pycache__				furl					numpy-1.11.3.dist-info			six-1.10.0.dist-info
_pytest					furl-0.4.2.dist-info			orderedmultidict			six.py
agent-0.1.2.dist-info			humanfriendly				orderedmultidict-0.7.11.dist-info	stevedore
agent.py				humanfriendly-2.1.dist-info		pandas					stevedore-1.2.0.dist-info
aiohttp					invoke					pandas-0.17.1.dist-info			tests
aiohttp-0.18.4.dist-info		invoke-0.11.1.dist-info			pbr					tornado
argparse-1.4.0.dist-info		ipython_genutils			pbr-0.11.1.dist-info			tornado-4.3.dist-info
argparse.py				ipython_genutils-0.1.0.dist-info	pip					traitlets
certifi					itsdangerous-0.24.dist-info		pip-9.0.1.dist-info			traitlets-4.2.2.dist-info
certifi-2015.04.28.dist-info		itsdangerous.py				pkg_resources				waterbutler
chardet					jinja2					py					waterbutler-0.19.0-py3.5-nspkg.pth
chardet-2.3.0.dist-info			jsonschema				py-1.4.32.dist-info			waterbutler-0.19.0-py3.5.egg-info
click					jsonschema-2.4.0.dist-info		pycodestyle-2.2.0.dist-info		werkzeug
click-6.6.dist-info			jupyter.py				pycodestyle.py				wheel
contextlib2-0.5.4.dist-info		jupyter_core				pydocx					wheel-0.29.0.dist-info
contextlib2.py				jupyter_core-4.2.1.dist-info		pyflakes				xlrd
coverage				mako					pyflakes-1.3.0.dist-info		xlrd-0.9.3-py3.5.egg-info
coverage-4.3.1.dist-info		markdown				pygments
dateutil				markupsafe				pytest-3.0.5.dist-info
decorator-4.0.10.dist-info		mccabe-0.5.3.dist-info			pytest-cov.pth
(mfr)`

**Comment by felliott** [comment]
Hey @rija,

We ran into this problem recently.  Running `invoke install -d` with setuptools v31 installed generates a namespace package that both MFR and WB don't like.  We pinned MFR to setuptools v30 with commit 7d8e8474a141742960e287d30ec3b56d8f2c5ca6, but unfortunately, manually downgrading setuptools won't be enough to fix this.  You'll need to:

1. Manually downgrade setuptools: `pip install setuptools==30.4.0`
2. Find the `site-packages` directory of your virtualenv and delete `waterbutler-nspkg.pth` and `mfr-nspkg.pth`.
3. `git pull` MFR so that you're up-to-date with the latest `master` or `develop`.
4. Re-run `invoke install -d` with setuptools v30

At this point it should start to work again.  If not, feel free to reopen this ticket!

Cheers,
Fitz
